@echo off
IF EXIST "../synth/__projnav" rmdir /S /Q "../synth/__projnav" 
IF EXIST "../synth/xst" rmdir /S /Q "../synth/xst" 
IF EXIST "../synth/_ngo" rmdir /S /Q "../synth/_ngo" 

IF EXIST _xmsgs rmdir /S /Q _xmsgs
IF EXIST icon_xdb rmdir /S /Q icon_xdb
IF EXIST ila_xdb rmdir /S /Q ila_xdb
IF EXIST tmp rmdir /S /Q tmp
IF EXIST vio_xdb rmdir /S /Q vio_xdb
IF EXIST xlnx_auto_0_xdb rmdir /S /Q xlnx_auto_0_xdb

IF EXIST coregen.cgp del /F /Q coregen.cgp
IF EXIST coregen.cgc del /F /Q coregen.cgc
IF EXIST coregen.log del /F /Q coregen.log
IF EXIST icon.asy del /F /Q icon.asy
IF EXIST icon.gise del /F /Q icon.gise
IF EXIST icon.ise del /F /Q icon.ise
IF EXIST icon.ngc del /F /Q icon.ngc
IF EXIST icon.xco del /F /Q icon.xco
IF EXIST icon.xise del /F /Q icon.xise
IF EXIST icon_flist.txt del /F /Q icon_flist.txt
IF EXIST icon_readme.txt del /F /Q icon_readme.txt
IF EXIST icon_xmdf.tcl del /F /Q icon_xmdf.tcl

IF EXIST ila.cdc del /F /Q ila.cdc
IF EXIST ila.gise del /F /Q ila.gise
IF EXIST ila.ise del /F /Q ila.ise
IF EXIST ila.ngc del /F /Q ila.ngc
IF EXIST ila.xco del /F /Q ila.xco
IF EXIST ila.xise del /F /Q ila.xise
IF EXIST ila_flist.txt del /F /Q ila_flist.txt
IF EXIST ila_readme.txt del /F /Q ila_readme.txt
IF EXIST ila_xmdf.tcl del /F /Q ila_xmdf.tcl

IF EXIST vio.cdc del /F /Q vio.cdc
IF EXIST vio.gise del /F /Q vio.gise
IF EXIST vio.ise del /F /Q vio.ise
IF EXIST vio.ngc del /F /Q vio.ngc
IF EXIST vio.xco del /F /Q vio.xco
IF EXIST vio.xise del /F /Q vio.xise
IF EXIST vio_flist.txt del /F /Q vio_flist.txt
IF EXIST vio_readme.txt del /F /Q vio_readme.txt
IF EXIST vio_xmdf.tcl del /F /Q vio_xmdf.tcl

IF EXIST ise_flow_results.txt del /F /Q ise_flow_results.txt
IF EXIST mem_interface_top.syr del /F /Q mem_interface_top.syr
IF EXIST smartpreview.twr del /F /Q  smartpreview.twr

IF EXIST RAMB16_S1.bgn del /F /Q  RAMB16_S1.bgn
IF EXIST RAMB16_S1_bitgen.xwbt del /F /Q  RAMB16_S1_bitgen.xwbt
IF EXIST RAMB16_S1.bit del /F /Q  RAMB16_S1.bit
IF EXIST RAMB16_S1.bld del /F /Q RAMB16_S1.bld
IF EXIST RAMB16_S1.drc del /F /Q  RAMB16_S1.drc
IF EXIST RAMB16_S1.ncd del /F /Q  RAMB16_S1.ncd
IF EXIST RAMB16_S1.ngc del /F /Q RAMB16_S1.ngc
IF EXIST RAMB16_S1_prev_built.ngd del /F /Q RAMB16_S1_prev_built.ngd
IF EXIST RAMB16_S1.ngd del /F /Q RAMB16_S1.ngd
IF EXIST RAMB16_S1.ngr del /F /Q RAMB16_S1.ngr
IF EXIST RAMB16_S1.pad del /F /Q  RAMB16_S1.pad
IF EXIST RAMB16_S1.par del /F /Q  RAMB16_S1.par
IF EXIST RAMB16_S1.pcf del /F /Q  RAMB16_S1.pcf
IF EXIST RAMB16_S1.ptwx del /F /Q  RAMB16_S1.ptwx
IF EXIST RAMB16_S1.twr del /F /Q  RAMB16_S1.twr
IF EXIST RAMB16_S1.twx del /F /Q  RAMB16_S1.twx
IF EXIST RAMB16_S1.unroutes del /F /Q  RAMB16_S1.unroutes
IF EXIST RAMB16_S1.ut del /F /Q  RAMB16_S1.ut
IF EXIST RAMB16_S1.xpi del /F /Q  RAMB16_S1.xpi
IF EXIST RAMB16_S1_map.map del /F /Q  RAMB16_S1_map.map
IF EXIST RAMB16_S1_map.mrp del /F /Q  RAMB16_S1_map.mrp
IF EXIST RAMB16_S1_map.ncd del /F /Q  RAMB16_S1_map.ncd
IF EXIST RAMB16_S1_map.ngm del /F /Q  RAMB16_S1_map.ngm
IF EXIST RAMB16_S1_map.xrpt del /F /Q  RAMB16_S1_map.xrpt
IF EXIST RAMB16_S1_ngdbuild.xrpt del /F /Q  RAMB16_S1_ngdbuild.xrpt
IF EXIST RAMB16_S1_pad.csv del /F /Q  RAMB16_S1_pad.csv
IF EXIST RAMB16_S1_pad.txt del /F /Q  RAMB16_S1_pad.txt
IF EXIST RAMB16_S1_par.xrpt del /F /Q  RAMB16_S1_par.xrpt
IF EXIST RAMB16_S1_summary.xml del /F /Q  RAMB16_S1_summary.xml
IF EXIST RAMB16_S1_usage.xml del /F /Q  RAMB16_S1_usage.xml

IF EXIST RAMB16_S1_vhdl.prj del /F /Q RAMB16_S1_vhdl.prj
IF EXIST RAMB16_S1_xst.xrpt del /F /Q RAMB16_S1_xst.xrpt
:: Files and folders generated by create ise
IF EXIST xst rmdir /S /Q xst 
IF EXIST _ngo rmdir /S /Q _ngo
IF EXIST test_xdb rmdir /S /Q test_xdb 
IF EXIST _xmsgs rmdir /S /Q _xmsgs 
IF EXIST test.ntrc_log del /F /Q test.ntrc_log
If EXIST RAMB16_S1.cmd_log del /F /Q RAMB16_S1.cmd_log
IF EXIST RAMB16_S1.lso del /F /Q  RAMB16_S1.lso
IF EXIST RAMB16_S1.ngc del /F /Q RAMB16_S1.ngc
IF EXIST RAMB16_S1.prj del /F /Q  RAMB16_S1.prj
IF EXIST RAMB16_S1.stx del /F /Q RAMB16_S1.stx
IF EXIST RAMB16_S1.syr del /F /Q RAMB16_S1.syr
IF EXIST RAMB16_S1.xst del /F /Q RAMB16_S1.xst
IF EXIST RAMB16_S1_summary.html del /F /Q  RAMB16_S1_summary.html
IF EXIST RAMB16_S1_usage.html del /F /Q  RAMB16_S1_usage.html
IF EXIST RAMB16_S1_prev_built.xst del /F /Q RAMB16_S1_prev_built.xst
IF EXIST RAMB16_S1_summary.xst del /F /Q RAMB16_S1_summary.xst
IF EXIST par_usage_statistics.html del /F /Q par_usage_statistics.html
IF EXIST usage_statistics_webtalk.html del /F /Q usage_statistics_webtalk.html
IF EXIST webtalk.log del /F /Q webtalk.log
IF EXIST device_usage_statistics.html del /F /Q	device_usage_statistics.html
IF EXIST RAMB16_S1_guide.ncd del /F /Q  RAMB16_S1_guide.ncd
IF EXIST test.gise del /F /Q test.gise
IF EXIST test.xise del /F /Q test.xise
IF EXIST test.xise del /F /Q test.xise

@echo on
